language: php
php:
  - '5.6'
  - '7.0'
  - nightly
  
before_script:
  - composer install

script:
  - phpunit

after_script:
    - vendor/bin/test-reporter --coverage-report="test/coverage/clover.xml"

addons:
    code_climate:
        repo_token: c6e81313f1bba8db61abbf41392fee5530cd222906449d615e63c45849bae893
